webtalk_init -webtalk_dir C:\\Xilinx\\Vivado\\Projects\\gitsim_python\\gitsim_python.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-07-09 13:14:35" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "v61uvg94d0ir4sbg4jmi6o9gr8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_399" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "399" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5600H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3294 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.477 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1720518576579" -context "sdk\\\\hardware/1720518576579"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1720518576579"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1720518576579"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1720518576579"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3" -context "sdk\\\\hardware/1720518576579"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1720518576579"
webtalk_add_data -client sdk -key Device -value "7z007s" -context "sdk\\\\hardware/1720518576579"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1720518576579"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1720518576579"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1720518576579"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1720518576579"
webtalk_add_data -client sdk -key uid -value "1720518614802" -context "sdk\\\\bsp/1720518614802"
webtalk_add_data -client sdk -key hwid -value "1720518576579" -context "sdk\\\\bsp/1720518614802"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1720518614802"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1720518614802"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1720518614802"
webtalk_add_data -client sdk -key uid -value "1720518616853" -context "sdk\\\\application/1720518616853"
webtalk_add_data -client sdk -key hwid -value "1720518576579" -context "sdk\\\\application/1720518616853"
webtalk_add_data -client sdk -key bspid -value "1720518614802" -context "sdk\\\\application/1720518616853"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1720518616853"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1720518616853"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1720518616853"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1720518616853"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1720518616853"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1720518616853"
webtalk_add_data -client sdk -key projSize -value "362.61328125" -context "sdk\\\\application/1720518616853"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1720523675000"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1720523675000"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1720523675000"
webtalk_add_data -client sdk -key DebugCount -value "19" -context "sdk\\\\bsp/1720523675000"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1720523675000"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1720523675000"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1720523675000"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1720523675000"
webtalk_transmit -clientid 1565439594 -regid "" -xml C:\\Xilinx\\Vivado\\Projects\\gitsim_python\\gitsim_python.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Xilinx\\Vivado\\Projects\\gitsim_python\\gitsim_python.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Xilinx\\Vivado\\Projects\\gitsim_python\\gitsim_python.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
